name: oshi
description: The hoshi of oshi's
publish_to: "none"
version: 9.9.9+9

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  darq: ^2.0.0
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  event: ^2.1.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  format: ^1.3.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  transparent_image: ^2.0.1
  uuid: ^4.1.0
  modal_bottom_sheet: ^3.0.0-pre
  url_launcher: ^6.1.14
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  pull_down_button: ^0.9.3
  dynamic_color: ^1.6.7
  visibility_detector: ^0.4.0+2
  flutter_linkify: ^6.0.0
  flutter_shake_animated: ^0.0.5
  visibility_aware_state: ^1.0.5
  version: ^3.0.2
  logging_to_logcat: ^1.0.0
  share_plus: ^7.2.1
  add_2_calendar: ^3.0.1
  flutter_swipe_action_cell: ^3.1.2
  duration: ^3.0.13
  equatable: ^2.0.5
  awesome_notifications: ^0.8.2
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/resources/strings/

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  color: "#ffffff"
  color_dark: "#1c1c1c"

  color_ios: "#ffffff"
  color_dark_ios: "#000000"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/resources/images/logo.png
  #image_dark: assets/splash-invert.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  #branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/resources/images/logo_fit.png
    #image_dark: assets/splash-invert.png

    # Splash screen background color.
    color: "#ffffff"
    color_dark: "#1c1c1c"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    #icon_background_color_dark: "#eeeeee"
