name: oshi
description: A new Flutter project.
publish_to: "none"
version: 9.9.9+9

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  darq: ^2.0.0
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  event: ^2.1.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  format: ^1.3.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  transparent_image: ^2.0.1
  uuid: ^4.1.0
  modal_bottom_sheet: ^3.0.0-pre
  url_launcher: ^6.1.14
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  pull_down_button: ^0.9.3
  dynamic_color: ^1.6.7
  visibility_detector: ^0.4.0+2
  flutter_linkify: ^6.0.0
  flutter_shake_animated: ^0.0.5
  visibility_aware_state: ^1.0.5
  version: ^3.0.2
  logging_to_logcat: ^1.0.0
  share_plus: ^7.2.1
  add_2_calendar: ^3.0.1
  flutter_swipe_action_cell: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
