# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Update versioning
        run: |
          sed -i '' "s/9.9.9.9/1.0.$(date '+%Y%m%d').${{github.run_number}}/g" ./lib/share/share.dart
          sed -i '' "s/9.9.9+9/1.0.$(date '+%Y%m%d')+${{github.run_number}}/g" ./lib/share/share.dart

      - name: Set up dependencies
        run: flutter pub get

      - name: Build for Android
        run: flutter build apk --target-platform android-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/Oshi.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Update versioning
        run: |
          sed -i '' "s/9.9.9.9/1.0.$(date '+%Y%m%d').${{github.run_number}}/g" ./lib/share/share.dart
          sed -i '' "s/9.9.9+9/1.0.$(date '+%Y%m%d')+${{github.run_number}}/g" ./lib/share/share.dart

      - name: Set up dependencies
        run: flutter pub get

      - name: Build for iOS
        run: |
          flutter build ios --release --no-codesign
          cd ./build/ios/iphoneos && mkdir Payload && mv Runner.app Payload/Runner.app && zip -r Oshi.ipa Payload

      - uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: build/ios/iphoneos/Oshi.ipa

  release:
    runs-on: macos-latest
    needs: [build-android, build-ios]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Set up environment
        run: echo "::set-env name=NOW::1.0.$(date '+%Y%m%d').${{github.run_number}}"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Upload build artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/android-release/app-release.apk,artifacts/ios-release/Oshi.ipa"
          tag: ${{ env.NOW }}
          token: ${{ secrets.GITHUB_TOKEN }}
