# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Update versioning
        run: sed -i '' "s/0.0.0.0/1.0.$(date '+%Y.%m.%d').${{github.run_number}}/g" ./lib/share/share.dart

      - name: Set up dependencies
        run: flutter pub get

      - name: Build for Android
        run: flutter build apk --target-platform android-arm64

      - name: Build for iOS
        run: |
          flutter build ios --release --no-codesign
          cd ./build/ios/iphoneos && mkdir Payload && mv Runner.app Payload/Runner.app && zip -r Oshi.ipa Payload

      - name: Set up environment
        run: echo "::set-env name=NOW::1.0.$(date '+%Y.%m.%d').${{github.run_number}}"

      - name: Upload build artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/Oshi.ipa"
          tag: ${{ env.NOW }}
          token: ${{ secrets.GITHUB_TOKEN }}