name: Flutter Web
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.KEY }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.3

      - name: Setup app secrets
        run: |
          sed -i '' "s/9.9.9+9/1.0.$(date '+%Y%m%d')/g" ./pubspec.yaml
          sed -i '' "s/9.9.9.9/1.0.$(date '+%Y%m%d').1/g" ./lib/share/share.dart
          sed -i '' "s/AZ_APPCENTER_TELEMETRY_TOKEN/${{ secrets.APPCENTER_TELEMETRY_TOKEN }}/g" ./lib/share/appcenter.dart
          sed -i '' "s/AZ_SZKOLNY_APP_TOKEN/${{ secrets.SZKOLNY_APP_TOKEN }}/g" ./lib/share/appcenter.dart

      - name: Build the web app
        run: |
          flutter pub get
          flutter build web --release --base-href /Oshi/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
          CLEAN: true